### ISSUE TITLE
unhandeled exception on setup

### ISSUE THREAD

**Issue by MovGP0** [ifedu/generator-speedseed#32]
I get an exception when trying to execute speedseed on a clean system:  

```
C:\Users\Johann\Documents\Test [master ≡]> npm i generator-speedseed -g
C:\Users\Johann\AppData\Roaming\npm\speedseed -> C:\Users\Johann\AppData\Roaming\npm\node_modules\generator-speedseed\bin\speedseed
C:\Users\Johann\AppData\Roaming\npm
`-- generator-speedseed@0.20.4

C:\Users\Johann\Documents\Test [master ≡]> speedseed install -g
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

C:\Users\Johann\Documents\Test  [master ≡]>
```

**Comment by ifedu** [comment]
Hello!

I do not manage to reproduce the error.

What nodejs version and of windows do you use?

**Comment by MovGP0** [comment]
Updated vom Node.js v4.4.7 (LTS) to v6.4.0 (Latest), which fixed it. Now it's working :-)

**Comment by ifedu** [comment]
Great! :)
